### ISSUE TITLE
Ubuntu 12.04 ruby path

### ISSUE THREAD

**Issue by directionless** [litaio/chef-lita#29]
When installing onto Ubuntu 12.04, the first converge fails to work. It results in runit trying to launch lita, and complaining that ruby 2.1 isn't found.

I think this is because the lita_runit_env stuff is weird. Perhaps it's generated on run start, and the ruby-ng installation doesn't end up updating it. 

Given that all the ruby installation methods are system package based (or backport styled), I removed the PATH override from lita_runit_env. Works for me

**Comment by harlanbarnes** [comment]
I think this is connected to the same issue as #28. That is, setting the env in your wrapper cookbook or role or environment or whatnot is the correct way to deal with it. If not, please re-open and I'll look again. Thanks!
