### ISSUE TITLE
Remove dependencies on ruby-ng and redis2

### ISSUE THREAD

**Issue by iroller** [litaio/chef-lita#7]
There are so many cookbooks to install ruby and redis nowadays that it doesn't make any sense to require user to upload those particular two cookbooks.

Even if you set "ruby_install_type" and "redis_install_type" to "none" it'll still require those cookbook to be on your chef-server:
```
% knife cookbook upload lita
Uploading lita           [0.0.3]
ERROR: Cookbook lita depends on cookbooks which are not currently
ERROR: being uploaded and cannot be found on the server.
ERROR: The missing cookbook(s) are: 'ruby-ng' version '~> 0.1.1', 'redis2' version '~> 0.5.0'
```

One option is to replace "depends" in metadata with "recommends" or "suggests":
https://docs.getchef.com/essentials_cookbook_metadata.html#settings

But using Berkshelf (which is a recommended way to manage cookbooks versions) they'll still be resolved and uploaded to the chef-server. You don't want any non-used cookbooks to be present on your chef-server, right?

I think having a section in docs just like https://github.com/opscode-cookbooks/jenkins#java should be enough for users to figure out dependencies and there's no need for ruby-ng and redis2 to be in chef-lita cookbook at all.

**Comment by harlanbarnes** [comment]
I've decided to leave this as-is long term. I was going to take on maintaining "mini-versions" of the rubyng and redis recipes in the  for those that wanted a turnkey solution. But that seems like a bad idea the more I think about it. I could be persuaded, but for now, I'm closing this.
